### PR TITLE
kd - issue #45: ensured uniqueness for PSCourse post. Added tests.

### LINKED ISSUE #45: Adjust `POST` method for `/api/courses/post` to enforce uniqueness within a given personal schedule
The `POST /api/courses/post` endpoint allows a user to add the same class multiple times.  This is not what we want.  The task is to modify the `postCourses` method in the `PSCourseController` class to refuse to add the same class twice to a user's`PersonalSchedule`.

Here is the fix.  Everything in the `postCourses` method before the line containing
```
ArrayList<PSCourse> savedCourses = new ArrayList<>();
```
exists solely to determine the enroll codes of the primary and secondary (if they exist) and put them into the variables `enrollCdPrimary` and `enrollCdSecondary`.  Because every class has a primary, you just need to check that the primary isn't already in the personal schedule.  The relevant method is located in `PSCourseRepository`:
```
  Optional<PSCourse> findByPsIdAndEnrollCd(long id, String enrollCd);
```
So before we add the course, we should have a check like:
```
if (coursesRepository.findByPsIdAndEnrollCd(psId, primaryEnrollCd).isPresent())
    throw new IllegalArgumentException("class exists in schedule");
```
After making this change, you should be unable to add a duplicate course.  Now to update the tests, you need to do two things:

1. Update all the existing `postCourses` tests with a
```when(coursesRepository.findByPsIdAndEnrollCd(/* personal schedule id here*/, /*primary enroll code here*/).thenReturn(Optional.empty())```
2. Copy one of the existing tests that ends in a successful insertion and just put ```when(coursesRepository.findByPsIdAndEnrollCd(/* personal schedule id here*/, /*primary enroll code here*/).thenReturn(Optional.of(/* course object here*/)```
and change the test to expect an `IllegalArgumentException`.  One test alone should be enough to get coverage and mutation coverage of the new lines added to `postCourses`.

### PR DESCRIPTION
**Pull request by dengkevin**
Closes #45.
Modified: PSCourseController.java and PSCourseControllerTests.java

In this PR, I check if enrollCdPrimary is not already in the personal schedule before adding it (ensuring no duplicate PSCourse posts). I also add test functionalities for the code I added. Testing includes coverage for all post methods checking for duplicate error.

### CODE REVIEW

File: src/test/java/edu/ucsb/cs156/courses/controllers/PSCourseControllerTests.java [hunk 1]
```diff
@@ -481,6 +515,8 @@ public void api_courses_post__user_logged_in__section_order_in_json_does_not_mat
 	PSCourse expectedSecondary = PSCourse.builder().enrollCd("08326").psId(1L).user(u).id(0L).build();
         when(coursesRepository.save(eq(expectedSecondary))).thenReturn(expectedSecondary);
 
+        when(coursesRepository.findByPsIdAndEnrollCd(eq(1L), eq("08326"))).thenReturn(Optional.empty());
```
Comment (eduglt) [inline src/test/java/edu/ucsb/cs156/courses/controllers/PSCourseControllerTests.java:518]: I think the enroll code should be "08292" since that's the primary enroll code and what gets checked in the `postCourses` implementation.

File: src/test/java/edu/ucsb/cs156/courses/controllers/PSCourseControllerTests.java [hunk 2]
```diff
@@ -447,6 +479,8 @@ public void api_courses_post__user_logged_in__secondary_enroll_code_adds_seconda
 	PSCourse expectedSecondary = PSCourse.builder().enrollCd("63388").psId(1L).user(u).id(0L).build();
         when(coursesRepository.save(eq(expectedSecondary))).thenReturn(expectedSecondary);
 
+        when(coursesRepository.findByPsIdAndEnrollCd(eq(1L), eq("63388"))).thenReturn(Optional.empty());
```
Comment (eduglt) [inline src/test/java/edu/ucsb/cs156/courses/controllers/PSCourseControllerTests.java:482]: I think the enroll code should be "63370" since that's the primary enroll code and what gets checked in the postCourses implementation.

**Review by eduglt — APPROVED** [review]
LGTM, thanks for changes!

**Review by pconrad — APPROVED** [review]
LGTM

File: src/main/java/edu/ucsb/cs156/courses/controllers/PSCourseController.java [hunk 3]
```diff
@@ -149,6 +149,9 @@ public ArrayList<PSCourse> postCourses(
 	    hasSecondary = false;
 	}
 
+    if (coursesRepository.findByPsIdAndEnrollCd(psId, enrollCdPrimary).isPresent()) {
```
Comment (pconrad) [inline src/main/java/edu/ucsb/cs156/courses/controllers/PSCourseController.java:152]: It's just embarrassing to see indentation issues this blatant in a PR that you are asking to merge into main.

Have we not taught you better than this .. not just in this course, but in all of your UCSB coding courses up to this point?

**Review by pconrad — CHANGES_REQUESTED** [review]
Definitely does NOT look good to me.

**Review by pconrad — APPROVED** [review]
Much better :-)
